Update requirements.txt
O Cloud não tem o openpyxl instalado, que é necessário para ler .xlsx.

O erro está dizendo exatamente isso:

ImportError: Missing optional dependency 'openpyxl'